#!/bin/bash

cd ~
mkdir -p ./config/nvim/
mkdir -p ./config/alacritty/

ln -si $HOME/dotfiles/bin bin
ln -si $HOME/dotfiles/ackrc .ackrc
ln -si $HOME/dotfiles/asdfrc .asdfrc
ln -si $HOME/dotfiles/gitconfig .gitconfig
ln -si $HOME/dotfiles/gitignoreglobal .gitignoreglobal
ln -si $HOME/dotfiles/psqlrc .psqlrc
ln -si $HOME/dotfiles/vim .vim
ln -si $HOME/dotfiles/vimrc .vimrc
ln -si $HOME/dotfiles/dotconfig/nvim/init.vim .config/nvim/init.vim
ln -si $HOME/dotfiles/dotconfig/nvim/coc-settings.json .config/nvim/coc-settings.json
ln -si $HOME/dotfiles/zshrc .zshrc
ln -si $HOME/dotfiles/ctagsignore .ctagsignore
ln -si $HOME/dotfiles/dotconfig/alacritty/alacritty.yml .config/alacritty/alacritty.yml
# used for update path to excludesfile in gitconfig file
git config --global core.excludesfile ~/.gitignoreglobal
