#!/bin/bash

cd ~
ln -si dotfiles/ackrc .ackrc
ln -si dotfiles/asdfrc .asdfrc
ln -si dotfiles/gitconfig .gitconfig
ln -si dotfiles/gitignoreglobal .gitignoreglobal
ln -si dotfiles/psqlrc .psqlrc
ln -si dotfiles/vim .vim
ln -si dotfiles/vimrc .vimrc
ln -si dotfiles/zshrc .zshrc
ln -si dotfiles/ctagsignore .ctagsignore
ln -si dotfiles/alacritty.yml .alacritty.yml
# used for update path to excludesfile in gitconfig file
git config --global core.excludesfile ~/.gitignoreglobal
