# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

[directory]
truncation_length = 5
style = "white"
before_repo_root_style = "white"
repo_root_style = "white"
# repo_root_format = 'repo:[$repo_root]($repo_root_style)[$read_only]($read_only_style) '
repo_root_format = '[repo:](white)[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) '

[character]
success_symbol = '[*](bold red)'
error_symbol = '[*](bold yellow)'
vimcmd_symbol = '[v](bold white)'

[battery]
full_symbol = "• "
charging_symbol = "⇡ "
discharging_symbol = "⇣ "
unknown_symbol = "❓ "
empty_symbol = "❗ "

[nodejs]
style = "white"
version_format = "${raw}"
symbol = "nodejs:"

[git_branch]
symbol = "git:"
style = "white"

[git_status]
style = "white"

[typst]
symbol = "t "

[jobs]
number_threshold = 1
symbol = "fg:"
style = "white"
